[package]
name = "ss-db"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
lapin = "4.7.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sqlx = { version = "0.8.6", features = ["postgres"] }
thiserror = "2.0.18"
tokio = { version = "1.52.2", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
